version: "3"        # 도커 컴포즈의 버전
services:           # 실행하고자 하는 컨테이너들
  redis-server:     # 컨테이너 이름
    image: "redis"  # 사용할 이미지
  node-app:         # 컨테이너 이름
    build: .        # 현재 디렉토리에 있는 Dockerfile을 사용하여 이미지를 빌드
    ports:          # 포트 매핑
      - "3000:8080" # 호스트의 5000번 포트와 컨테이너의 8080번 포트를 연결