version: "3"                      # 도커 컴포즈 버전
services:                          # 실행할 컨테이너들을 정의
  react:                          # 컨테이너 이름
    build:                        # 도커 이미지를 빌드할 때 사용할 Dockerfile을 지정
      context: .                  # Dockerfile이 있는 경로
      dockerfile: Dockerfile.dev  # 사용할 Dockerfile 이름
    ports:                        # 컨테이너 이름
      - "3000:3000"               # 포트 매핑
    volumes:                      # 볼륨을 사용하여 소스코드 변경 시 자동으로 반영
      - /usr/src/app/node_modules # node_modules 디렉토리는 컨테이너에 복사하지 않음
      - ./:/usr/src/app           # 현재 디렉토리를 컨테이너의 /usr/src/app 디렉토리에 마운트
    stdin_open: true              # 컨테이너가 실행되면 표준 입력을 열어줌
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["npm", "run", "test"]