name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build Docker Image and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t dbtnss/docker-react-app -f /docker-react-app/Dockerfile.dev .

    - name: Run npm install
      run: npm install

    - name: Run Tests
      run: npm run test

    - name: Check test results
      run: |
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "Test Success"
        else
          echo "Test Failed"
          exit 1
        fi